## Data Manipulation

n-dimensional array aka tensor

similar to ndarray from numpy with some killer features. 
 - gpu suppoted to accelerate the coputation
 - tensor class supports automatic differentiation
 
 hence widely used for deep learning

 Level | Level for Humans | Level Description                  
 -------|------------------|------------------------------------ 
  0     | DEBUG            | [Default] Print all messages       
  1     | INFO             | Filter out INFO messages           
  2     | WARNING          | Filter out INFO & WARNING messages 
  3     | ERROR            | Filter out all messages      

In [28]:
import tensorflow as tf
tf.get_logger().setLevel('INFO')

1 axis tensor = vector

2 axis tensors = matrix

3 or more axis = no mathematical name.

In [29]:
x = tf.range(12)
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [30]:
x.shape

TensorShape([12])

if we want total number of elements in the tensor, (multiplication of values in shape), use the following

In [31]:
tf.size(x)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [32]:
x = tf.reshape(x, (3, 4))
x.shape

TensorShape([3, 4])

dont have to mention all dimensions in reshape function. put -1 in one value, tf will automatically find out the rest. 

In [33]:
x = tf.reshape(x, (-1, 3))
x.shape

TensorShape([4, 3])

we can initialize with zero/constants/random samples from a distribution. 

can be done like below

In [34]:
tf.zeros((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [35]:
tf.ones((2, 3, 4))

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [36]:
tf.random.normal(shape = [3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.74358493,  1.2950714 ,  0.17888027, -0.8747478 ],
       [-0.28568903,  0.9913342 ,  1.000515  , -0.21819799],
       [-0.36157808,  1.6532161 ,  0.41357896, -1.3824923 ]],
      dtype=float32)>

we can also specify exact values using python lists or ndarrays. 

In [37]:
tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

### Operations on Tensors

In [38]:
x = tf.range(5,10)
y = tf.range(11,16)

In [39]:
x, y

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([11, 12, 13, 14, 15], dtype=int32)>)

In [40]:
x+y, x-y, x*y, x/y, x**y

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16, 18, 20, 22, 24], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([-6, -6, -6, -6, -6], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 55,  72,  91, 112, 135], dtype=int32)>,
 <tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.45454545, 0.5       , 0.53846154, 0.57142857, 0.6       ])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=
 array([   48828125, -2118184960, -1895237401,           0, -1010140999],
       dtype=int32)>)

In [41]:
tf.math.exp(5.5)

<tf.Tensor: shape=(), dtype=float32, numpy=244.69194>

we can also concatenate multiple tensors to form a larger tensor. 

axis 0 -> first element of tf.shape

axis 1 -> second element of tf.shape

In [42]:
x = tf.reshape(tf.range(12, dtype = tf.float32), (3, 4))
y = tf.reshape(tf.range(12, 24, dtype = tf.float32), (3, 4))

In [43]:
tf.concat([x, y], axis = 0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]], dtype=float32)>

In [44]:
tf.concat([x, y], axis = 1)

<tf.Tensor: shape=(3, 8), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3., 12., 13., 14., 15.],
       [ 4.,  5.,  6.,  7., 16., 17., 18., 19.],
       [ 8.,  9., 10., 11., 20., 21., 22., 23.]], dtype=float32)>

we can create binary tensors using comparision operators

In [45]:
x == y 

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

summing all elements in tensors yields tensor with only one element

In [46]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=66.0>

### Broadcasting Mechanism

broadcasting : lets operations be performed on tensors of uneven size by expanding one or both tensors to a compatible shape

In [47]:
a = tf.reshape(tf.range(3), (3, 1))
a

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2]], dtype=int32)>

In [48]:
b = tf.reshape(tf.range(2), (1, 2))
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>

In [49]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]], dtype=int32)>

indexing is just like in normal python lists

### Saving Memory

executing operations on tensors can sometimes cause the result to be hosted at a different memory locaiton. 

this is undesirable because we want to make optimal usage of memory and there might be hundreds of operations left. 

so we want to perform these operations _in place_ 

if this is not done, other references will still point to the old location leading to references to stale parameters 

In [50]:
x = tf.range(12)
y = tf.range(13, 25)
print(id(x))
print(id(y))
y = x + y
print(id(y))

140559534111632
140559534112400
140559534110864


In [51]:
z = tf.Variable(tf.zeros_like(y))
print(id(z))
z.assign(x + y)
print(id(z))

140559382291984
140559382291984


even when tf.Variable is used, it is better not to use it when not needed because, tensorflow tensors are immutable and gradients do not flow through variable assignments.

but tensorflow provides tf.function decorator to wrap computation inside a tensorflow graph that gets compiled and optimized before running. 

this allows tf to prune unused values and reuse prior allocations and no longer needed. 

this minimizes the memory overhead of tensorflow computations

In [52]:
@tf.function
def computation(x, y):
    z = tf.zeros_like(y)
    a = x+y
    b = a+y
    c = b+y
    return c+y

computation(x, y)

<tf.Tensor: shape=(12,), dtype=int32, numpy=
array([ 52,  61,  70,  79,  88,  97, 106, 115, 124, 133, 142, 151],
      dtype=int32)>

when tensorflow arrays are converted to other datatypes (ndarrays for ex) they do not share memory. this detail needs more attention as it could lead to computation halts because the memory is being used by numpy when needed

In [53]:
a = x.numpy()
b = tf.constant(a)
type(a), type(b)

(numpy.ndarray, tensorflow.python.framework.ops.EagerTensor)

to convert a size 1 tensor to a python scalar, we use item function or other python functions

In [54]:
a = tf.constant([3.5]).numpy()
a, a.item(), float(a), int(a)

(array([3.5], dtype=float32), 3.5, 3.5, 3)

## Data Preprocessing

creating temp dataset

In [66]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # Column names
    f.write('NA,Pave,127500\n')  # Each row represents a data example
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [79]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [68]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


/home/asrjy/miniconda3/envs/ml/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  


In [71]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [76]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [77]:
X, y = tf.constant(inputs.values), tf.constant(outputs.values)
X, y

(<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
 array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]])>,
 <tf.Tensor: shape=(4,), dtype=int64, numpy=array([127500, 106000, 178100, 140000])>)

### Exercises

In [85]:
data = pd.read_csv(data_file)
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [86]:
inputs = inputs.drop('Alley', axis = 1)

In [90]:
X = tf.constant(inputs)
X

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[3.],
       [2.],
       [4.],
       [3.]])>

## Linear Algebra

In [ ]:
x ∈ R means x in R

scalar in tensorflow = tensor with just one element

In [91]:
x = tf.constant(3.0)
y = tf.constant(5.0)

x+y, x-y, x*y, x/y, x**y

(<tf.Tensor: shape=(), dtype=float32, numpy=8.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=15.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.6>,
 <tf.Tensor: shape=(), dtype=float32, numpy=242.99998>)

vector = list of scalar values. 

In [93]:
x = tf.range(4)
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>